openapi: 3.0.0
info:
  title: ScalarTax
  description : Custom Tax Codes Rules API Documentation
  version: 1.0.0
  contact:
    name: API Support
    url: http://example.com/supportt
    email: support@example.com
  termsOfService: http://example.com/terms/
servers:
  - url: http://localhost:3001/scalarhubio
    description: Local server
paths:  
  /scalartax/custom_tax_codes/:
    post:
      tags:
        - Custom Tax Codes
      summary: Create Custom Tax Code
      description: This endpoint allows you to add a new Custom Tax Code.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomTaxCode"
              example:
                tax_code_type: string
                entity_id: string
                code: string
                description: string
        description: Custom Tax Code object
        required: true  
      responses:
        '201':
          description: Custom Tax Code Created successfully  
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomTaxCode1"
                example:
                  id: string
                  entity_id: string
                  tax_code_type: string
                  code: string
                  description: string
                  Description of custom tax code: null
                  created_by_id: string
                  updated_by_id: string
                  created_at: string (date-time)
                  updated_at: string (date-time)
        '422':
          description:  Unprocessable Entity. Validation errors occurred during the creation.
          content:
            application/json:
              schema:
                type: object
                example:
                  errors: [ Failed to Create Custom Tax Code ]
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error.
    get:
      tags:
        - Custom Tax Codes
      summary: List Custom Tax Codes
      description: This endpoint retrieves the details of all Custom Tax Codes.
      responses:
        '200':
          description: OK   
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomTaxCode1"
                example:
                  - id: string
                    entity_id: string
                    tax_code_type: string
                    code: string
                    description: string
                    Description of custom tax code: null
                    created_by_id: string
                    updated_by_id: string
                    created_at: string (date-time)
                    updated_at: string (date-time)
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /scalartax/custom_tax_codes/{id}:
    get:
      tags:
        - Custom Tax Code
      summary: Fetch Custom Tax Code
      description: The response will include the following details of the Custom Tax Code.
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomTaxCode1"
                example:
                  id: string
                  entity_id: string
                  tax_code_type: string
                  code: string
                  description: string
                  Description of custom tax code: null
                  created_by_id: string
                  updated_by_id: string
                  created_at: string (date-time)
                  updated_at: string (date-time)
        '404':
          description: Not Found.Custom Tax Code with that Specific ID not Found.
          content:
            application/json:
              schema:
                type: object
                example:
                  error: Custom Tax Code Not Found.
        '500':
          description: Internal Serval Error.
    put:
      tags:
        - Custom Tax Code
      summary: Update Custom Tax Code
      description: This API endpoint is used to update the details of a specific Custom Tax Code for a tenant.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomTaxCode"
              example:
                tax_code_type: string
                entity_id: string
                code: string
                description: string
        description: Custom tax Code object
        required: true 
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK.Custom Tax Code Updated Successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomTaxCode1"
                example:
                  id: string
                  entity_id: string
                  tax_code_type: string
                  code: string
                  description: string
                  Description of custom tax code: null
                  created_by_id: string
                  updated_by_id: string
                  created_at: string (date-time)
                  updated_at: string (date-time)
        '400':
          description: Bad Request
        '404':
          description: Not Found.Custom Tax Code with that Specific ID not Found.
          content:
            application/json:
              schema:
                type: object
                example:
                  error: Custom Tax Code Not Found.
        '422':
          description: Unprocessable Entity. Validation errors occurred during the update.
          content:
            application/json:
              schema:
                type: object
                example:
                  errors: [ Product code can't be blank,Category is invalid ]
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Custom Tax Code
      summary: Delete Custom Tax Code
      description: This endpoint is used to delete a specific Custom Tax Code belonging to a tenant.
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Ok. Custom Tax Code Deleted successfully  
        '404':
          description: Not Found.Custom Tax Code with the Specific ID not Found.
          content:
            application/json:
              schema:
                type: object
                example:
                  error: Failed to delete the Tax Rule
        '500':
          description: Internal Server Error
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CustomTaxCode:
      type: object
      properties:
        tax_code_type:
          type: string
          description: Type of the tax code (e.g., product, service)
        entity_id:
          type: string
          description: Unique identifier for the entity associated with the tax code
        code:
          type: string
          description: Unique tax code
        description:
          type: string
          description: Description of the tax code
      required:
        - tax_code_type
        - entity_id
        - code
        - description
    CustomTaxCode1:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the custom tax code
        entity_id:
          type: string
          description: Unique identifier for the associated entity
        tax_code_type:
          type: string
          description: Type of tax code (e.g., product, service)
        code:
          type: string
          description: The unique code for the tax type
        description:
          type: string
          description: Description of the tax code
        Description_of_custom_tax_code:
          type: string
          nullable: true
          description: Optional description for a custom tax code
        created_by_id:
          type: string
          description: Identifier of the user who created the custom tax code
        updated_by_id:
          type: string
          description: Identifier of the user who last updated the custom tax code
        created_at:
          type: string
          format: date-time
          description: Date and time when the custom tax code was created
        updated_at:
          type: string
          format: date-time
          description: Date and time when the custom tax code was last updated
      required:
        - id
        - entity_id
        - tax_code_type
        - code
        - description
        - created_by_id
        - updated_by_id
        - created_at
        - updated_at

  