openapi: 3.0.0
info:
  title: ScalarTax
  description : Location Attribute API Documentation
  version: 1.0.0
  contact:
    name: API Support
    url: http://example.com/supportt
    email: support@example.com
  termsOfService: http://example.com/terms/
servers:
  - url: http://localhost:3001/scalarhubio
    description: Local server
paths:
  /scalartax/location_attributes:
    post:
      tags:
        - Location Attributes
      summary: Create Location Attribute
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Create_Location_attributes"
        description: Location Attribute object
        required: true
      responses:
        '201':
          description: Location Attribute Created Successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Create_Location_attributes"
                example: 
                  location_attributes:
                    - location_id: "LOC123"
                      attribute_name: "Temperature"
                      attribute_value: "25"
                      attribute_unit_of_measure: "Celsius"
                      updated_by_id: "USR202411291616208c43ff3d3bf0404"
                      created_by_id: "USR202411291616208c43ff3d3bf0404"

        '422':
          description:  Unprocessable Entity. Validation errors occurred during the creation.
          content:
            application/json:
              schema:
                type: object
                example:
                  errors: [ Attribute value can't be blank ]
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    get:
      tags:
        - Location Attributes
      summary: List Location Attributes
      parameters:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                example: 
                  - id: string
                    location_id: string
                    attribute_name: string
                    attribute_value: string
                    attribute_unit_of_measure: string
                    updated_by_id: null | string
                    created_by_id: null | string
                    created_at: datetime
                    updated_at: datetime
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /scalartax/location_attributes/{id}:
    get:
      tags:
        - Location Attributes
      summary: Fetch Location Attribute
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            applicaiotn/json:
              schema:
                type: object
                example:
                  id: string
                  location_id: string
                  attribute_name: string
                  attribute_value: string
                  attribute_unit_of_measure: string
                  updated_by_id: null | string
                  created_by_id: null | string
                  created_at: datetime
                  updated_at: datetime
        '404':
          description: Not Found. Location Attribute with that Specific ID not Found.
          content:
            application/json:
              schema:
                type: object
                example:
                  error: Location Attribute Not Found.
        '500':
          description: Internal Serval Error.
    put:
      tags:
        - Location Attributes
      summary: Update Location Attribute
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Update_Location_attribute"
        required: true
      responses:
        '200':
          description: OK. Location Attribute Updates Successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Update_Location_attribute"
                example: 
                  attribute_name: string
                  attribute_value: string
                  attribute_unit_of_measure: string
                  updated_by_id: string
                  id: string
                  location_id: string
                  created_by_id: string
                  created_at: datetime
                  updated_at: datetime
        '400':
          description: Bad Request
        '404':
          description: Not Found. Location Atttribute with that Specific ID not Found.
          content:
            application/json:
              schema:
                type: object
                example:
                  error: Location Attribute Not Found.
        '422':
          description: Unprocessable Entity. Validation errors occurred during the update.
          content:
            application/json:
              schema:
                type: object
                example:
                  errors: [Attribute value can't be blank]      
        '500':
          description: Internal Serval Error
    delete:
      tags:
        - Location Attributes
      summary: Delete Location Attribute
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK. Location Attribute Deletd Successfully.
        '404':
          description: Not Found. Location Attribute with the Specific ID not Found.
          content:
            application/json:
              schema:
                type: object
                example:
                  error: Location Attribute Not Found.
        '500':
          description: Internal Server Error

components:
  schemas:
    Create_Location_attributes:
      type: object
      properties:
        location_attributes:
          type: array
          items:
            type: object
            properties:
              location_id:
                type: string
                description: "Unique identifier for the location"
              attribute_name:
                type: string
                description: "Name of the attribute (e.g., Temperature)"
              attribute_value:
                type: string
                description: "The value of the attribute (e.g., 25)"
              attribute_unit_of_measure:
                type: string
                description: "The unit of measurement for the attribute (e.g., Celsius)"
              created_by_id:
                type: string
                description: "The ID of the user who created the record"
              updated_by_id:
                type: string
                description: "The ID of the user who last updated the record"
            required:
            - location_id
              - attribute_name
              - attribute_value
              - attribute_unit_of_measure
              - created_by_id
              - updated_by_id
    Update_Location_attribute:
      type: object
      description: "Represents the attributes of a location, including identification and measurements."
      properties:
        location_attribute:
          type: object
          properties:
            location_id:
              type: string
              description: "Unique identifier for the location."
            attribute_name:
              type: string
              description: "The name of the attribute being measured (e.g., 'Temperature')."
            attribute_value:
              type: string
              description: "The value of the attribute (e.g., '25')."
            attribute_unit_of_measure:
              type: string
              description: "The unit of measure for the attribute (e.g., 'Celsius')."
            created_by_id:
              type: string
              description: "ID of the user who created this record."
            updated_by_id:
              type: string
              description: "ID of the user who last updated this record."
          required:
            - location_id
            - attribute_name
            - attribute_value
            - attribute_unit_of_measure
            - created_by_id
            - updated_by_id
    