openapi: 3.0.0
info:
  title: ScalarTax
  description : S_l_Nexuses API Documentation
  version: 1.0.0
  contact:
    name: API Support
    url: http://example.com/supportt
    email: support@example.com
  termsOfService: http://example.com/terms/
servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: http://{{base_url}}/
    description: Local server
paths:
  /scalartax/s_l_nexuses:
    post:
      tags:
        - S_l_Nexuses
      summary: Create S_l_Nexus
      description: This endpoint allows the user to add a nexus for tenants.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/S_l_Nexus"
              example:
                nexuses:
                  - entity_id: string
                    country: string
                    region: string
                    juris_type_id: integer
                    jurisdiction_type_id: integer
                    juris_code: string
                    juris_name: string
                    effective_date: string (ISO date)
                    end_date: null
                    short_name: string
                    signature_code: string
                    state_assigned_no: string
                    nexus_type_id: integer
                    sourcing: string
                    has_local_nexus: boolean
                    local_nexus_type_id: integer
                    has_permanent_establishment: boolean
                    tax_id: string
                    streamlined_sales_tax: boolean
                    is_sst_active: boolean
                    created_by_id: integer
                    updated_by_id: integer
                    tax_type_group: string
                    nexus_tax_type_group: string
                    is_seller_importer_of_record: boolean
                    tax_name: string
                    taxable_nexus: boolean
        description: S_l_Nexus object
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/S_l_Nexus"
                example: 
                  message: Records created successfully
        '422':
          description:  Unprocessable Entity. Validation errors occurred during the creation.
          content:
            application/json:
              schema:
                type: object
                example:
                  errors: [ Valid Error Message ]
        '400':
          description: Bad Request.Malformed request or invalid data.
        '500':
          description: Internal Server Error
    get:
      tags:
        - S_l_Nexuses
      summary: List S_l_Nexuses
      description: This endpoint retrieves the nexuses for the specific tenants.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                example:
                  - id: string
                    entity_id: string
                    country: string
                    region: string
                    juris_type_id: integer
                    jurisdiction_type_id: integer
                    juris_code: string
                    juris_name: string
                    effective_date: string (ISO date)
                    end_date: null
                    short_name: string
                    signature_code: string
                    state_assigned_no: string
                    nexus_type_id: integer
                    sourcing: string
                    has_local_nexus: boolean
                    local_nexus_type_id: integer
                    has_permanent_establishment: boolean
                    tax_id: string
                    streamlined_sales_tax: boolean
                    is_sst_active: boolean
                    created_by_id: string
                    updated_by_id: string
                    tax_type_group: string
                    nexus_tax_type_group: string
                    is_seller_importer_of_record: boolean
                    tax_name: string
                    taxable_nexus: boolean
                    created_at: datetime
                    updated_at: datetime
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error                      
  /scalartax/s_l_nexuses/{id}:
    get:
      tags:
        - S_l_Nexuses
      summary: Fetch S_l_Nexus
      description: This endpoint retrieves information about a specific nexus for a given tenant.
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/S_l_Nexus"
                example:
                  id: string
                  entity_id: string
                  country: string
                  region: string
                  juris_type_id: integer
                  jurisdiction_type_id: integer
                  juris_code: string
                  juris_name: string
                  effective_date: string (ISO date)
                  end_date: null
                  short_name: string
                  signature_code: string
                  state_assigned_no: string
                  nexus_type_id: integer
                  sourcing: string
                  has_local_nexus: boolean
                  local_nexus_type_id: integer
                  has_permanent_establishment: boolean
                  tax_id: string
                  streamlined_sales_tax: boolean
                  is_sst_active: boolean
                  created_by_id: string
                  updated_by_id: string
                  tax_type_group: string
                  nexus_tax_type_group: string
                  is_seller_importer_of_record: boolean
                  tax_name: string
                  taxable_nexus: boolean
                  created_at: datetime
                  updated_at: datetime                
        '404':
          description: Not Found. S_l_Nexus with that Specific ID not Found.
          content:
            application/json:
              schema:
                type: object
                example:
                  error: S_l_Nexus Not Found.
        '500':
          description: Internal Serval Error.
    put:
      tags:
        - S_l_Nexuses
      summary: Update S_l_Nexus
      description: This endpoint allows the user to update the nexus information for a specific tenant.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/S_l_Nexus"
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/S_l_Nexus"
                example:
                  message : Records updated and created successfully
        '400':
          description: Bad Request. Malformed request or invalid data.
        '422':
          description: Unprocessable Entity. Validation errors occurred during the update.
          content:
            application/json:
              schema:
                type: object
                example:
                  errors: [Validation error message]
        '404':
          description: Not Found. S_l_Nexus with that Specific ID not Found.
          content:
            application/json:
              schema:
                type: object
                example:
                  error: S_l_Nexus Not Found.
        '500':
          description: Internal Serval Error
    delete:
      tags:
        - S_l_Nexuses
      summary: Delete S_l_Nexus
      description: This endpoint is used to delete a specific nexus for a tenant.
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description:OK. Customer deleted successfully
        '404':
          description: Not Found. S_l_Nexus with the Specific ID not Found.
          content:
            application/json:
              schema:
                type: object
                example:
                  error: S_l_Nexus Not Found.
        '500':
          description: Internal Server Error

components: 
  schemas:
    S_l_Nexus:
      type: object
      properties:
        nexuses:
          type: array
          description: List of nexus records
          items:
            type: object
            properties:
              entity_id:
                type: string
                description: The unique ID of the entity
                required: true
              country:
                type: string
                description: The country code (e.g., "US")
                required: true
              region:
                type: string
                description: The region or state code (e.g., "CA")
                required: true
              juris_type_id:
                type: integer
                description: The jurisdiction type ID
                required: true
              jurisdiction_type_id:
                type: integer
                description: The jurisdiction type ID
                required: true
              juris_code:
                type: string
                description: The jurisdiction code (e.g., "CA123")
                required: true
              juris_name:
                type: string
                description: The name of the jurisdiction (e.g., "California")
                required: true
              effective_date:
                type: string
                format: date
                description: The effective date of the nexus
                required: true
              end_date:
                type: string
                format: date
                nullable: true
                description: The end date of the nexus, if applicable
                required: false
              short_name:
                type: string
                description: The short name for the jurisdiction (e.g., "CA")
                required: true
              signature_code:
                type: string
                description: Signature code related to the nexus
                required: false
              state_assigned_no:
                type: string
                description: State-assigned number for the nexus
                required: false
              nexus_type_id:
                type: integer
                description: The nexus type ID
                required: true
              sourcing:
                type: string
                description: Sourcing method, e.g., "destination"
                required: true
              has_local_nexus:
                type: boolean
                description: Indicates whether there is local nexus
                required: false
              local_nexus_type_id:
                type: integer
                description: The local nexus type ID
                required: false
              has_permanent_establishment:
                type: boolean
                description: Indicates whether there is a permanent establishment
                required: false
              tax_id:
                type: string
                description: The tax ID associated with the nexus
                required: false
              streamlined_sales_tax:
                type: boolean
                description: Indicates if the nexus is part of the Streamlined Sales Tax program
                required: false
              is_sst_active:
                type: boolean
                description: Indicates if the Streamlined Sales Tax is active
                required: false
              created_by_id:
                type: integer
                description: ID of the user who created the nexus
                required: true
              updated_by_id:
                type: integer
                description: ID of the user who last updated the nexus
                required: true
              tax_type_group:
                type: string
                description: Group of tax types applicable to the nexus (e.g., "Sales")
                required: false
              nexus_tax_type_group:
                type: string
                description: The nexus tax type group (e.g., "Retail")
                required: false
              is_seller_importer_of_record:
                type: boolean
                description: Indicates whether the seller is the importer of record for tax purposes
                required: false
              tax_name:
                type: string
                description: The name of the tax (e.g., "Sales Tax")
                required: true
              taxable_nexus:
                type: boolean
                description: Indicates whether the nexus is taxable
                required: true
            required:
              - entity_id
              - country
              - region
              - juris_type_id
              - juridiction_type_id
              - juris_code
              - juris_name
              - effective_date
              - short_name
              - nexus_type_id
              - sourcing
              - created_by_id
              - updated_by_id
              - tax_name
              - taxable_nexus
      required:
        nexuses