openapi: 3.0.0
info:
  title: ScalarTax
  description : Tax Rules API Documentation
  version: 1.0.0
  contact:
    name: API Support
    url: http://example.com/supportt
    email: support@example.com
  termsOfService: http://example.com/terms/
servers:
  - url: http://localhost:3001/scalarhubio
    description: Local server
paths:  
  /scalartax/tax_rules/:
    post:
      tags:
        - Tax Rules
      summary: Create Tax Rule
      description: This endpoint allows you to add a new Tax Rule.   
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaxRule"
              example: 
                name: string
                entity_id: string
                process_code: string
                tax_type_group: string
                country: string
                region: string
                jurisdiction_type: string
                juris_code: string
                jurisdiction_name: string
                is_all_juris: boolean
                tax_code: string
                tariff_code: string
                entity_use_code: string
                tax_type: string
                rate_type: string
                value: float
                threshold: float
                cap: float
                is_pro: boolean
                effective_date: string (date)
                expiration_date: string (date)
                description: string
                rate: float
                source: string
                cap_applied_value: float
                cap_option: string
                threshold_applied_value: float
                tax_entire_amount: boolean
                options:
                  additional_info: string
                  exemptions: array of strings
        description: TaxRule object
        required: true    
      responses:
        '201':
          description: Tax Rule Created successfully 
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaxRule1"
                example:
                  id: string
                  name: string
                  rule_type: null
                  process_code: string
                  tax_type_group: string
                  tax_sub_type: null
                  country: string
                  region: string
                  jurisdiction_type: string
                  juris_code: string
                  jurisdiction_name: string
                  is_all_juris: boolean
                  tax_code: string
                  tariff_code: string
                  entity_use_code: string
                  tax_type: string
                  rate_type: string
                  value: float
                  threshold: float
                  cap: float
                  options:
                    additional_info: string,
                    exemptions: array of strings
                  is_pro: boolean
                  effective_date: string (date)
                  expiration_date: string (date)
                  description: string
                  rate: float
                  source: string
                  created_by_id: string
                  updated_by_id: string
                  created_at: string (date-time)
                  updated_at: string (date-time)
                  entity_id: string
                  cap_applied_value: float
                  cap_option: string
                  threshold_applied_value: float
                  tax_entire_amount: boolean
        '422':
          description:  Unprocessable Entity. Validation errors occurred during the creation.
          content:
            application/json:
              schema:
                type: object
                example:
                  errors: [ Failed to Create Tax Rule ]
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error.
    get:
      tags:
        - Tax Rules
      summary: List Tax Rules
      description: This endpoint retrieves the details of all Tax Rules.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaxRule1"
                example:
                  - id: string
                    name: string
                    rule_type: null
                    process_code: string
                    tax_type_group: string
                    tax_sub_type: null
                    country: string
                    region: string
                    jurisdiction_type: string
                    juris_code: string
                    jurisdiction_name: string
                    is_all_juris: boolean
                    tax_code: string
                    tariff_code: string
                    entity_use_code: string
                    tax_type: string
                    rate_type: string
                    value: float
                    threshold: float
                    cap: float
                    options:
                      additional_info: string,
                      exemptions: array of strings
                    is_pro: boolean
                    effective_date: string (date)
                    expiration_date: string (date)
                    description: string
                    rate: float
                    source: string
                    created_by_id: string
                    updated_by_id: string
                    created_at: string (date-time)
                    updated_at: string (date-time)
                    entity_id: string
                    cap_applied_value: float
                    cap_option: string
                    threshold_applied_value: float
                    tax_entire_amount: boolean
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /scalartax/tax_rules/{id}:
    get:
      tags:
        - Tax Rules
      summary: Fetch Tax Rule
      description: The response will include the following details of the Tax Rule.
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaxRule1"
                example:
                  id: string
                  name: string
                  rule_type: null
                  process_code: string
                  tax_type_group: string
                  tax_sub_type: null
                  country: string
                  region: string
                  jurisdiction_type: string
                  juris_code: string
                  jurisdiction_name: string
                  is_all_juris: boolean
                  tax_code: string
                  tariff_code: string
                  entity_use_code: string
                  tax_type: string
                  rate_type: string
                  value: float
                  threshold: float
                  cap: float
                  options:
                    additional_info: string,
                    exemptions: array of strings
                  is_pro: boolean
                  effective_date: string (date)
                  expiration_date: string (date)
                  description: string
                  rate: float
                  source: string
                  created_by_id: string
                  updated_by_id: string
                  created_at: string (date-time)
                  updated_at: string (date-time)
                  entity_id: string
                  cap_applied_value: float
                  cap_option: string
                  threshold_applied_value: float
                  tax_entire_amount: boolean
        '404':
          description: Not Found. Tax Rule with that Specific ID not Found.
          content:
            application/json:
              schema:
                type: object
                example:
                  error: Tax Rule Not Found.
        '500':
          description: Internal Serval Error.
    put:
      tags:
        - Tax Rules
      summary: Update Tax Rule
      description: This API endpoint is used to update the details of a specific Tax Rule for a tenant.
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaxRule"
              example:
                name: string
                entity_id: string
                process_code: string
                tax_type_group: string
                country: string
                region: string
                jurisdiction_type: string
                juris_code: string
                jurisdiction_name: string
                is_all_juris: boolean
                tax_code: string
                tariff_code: string
                entity_use_code: string
                tax_type: string
                rate_type: string
                value: float
                threshold: float
                cap: float
                is_pro: boolean
                effective_date: string (date)
                expiration_date: string (date)
                description: string
                rate: float
                source: string
                cap_applied_value: float
                cap_option: string
                threshold_applied_value: float
                tax_entire_amount: boolean
                options:
                  additional_info: string
                  exemptions: array of strings
        required: true
      responses:
        '200':
          description: OK. Tax Rule Updated Successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaxRule2"
                example:
                    id: string
                    name: string
                    entity_id: string
                    rule_type: string (nullable)
                    process_code: string
                    tax_type_group: string
                    tax_sub_type: string (nullable)
                    country: string
                    region: string
                    jurisdiction_type: string
                    juris_code: string
                    jurisdiction_name: string (nullable)
                    is_all_juris: boolean
                    tax_code: string
                    tariff_code: string
                    entity_use_code: string
                    tax_type: string
                    rate_type: string
                    value: string
                    threshold: string
                    cap: string
                    is_pro: boolean
                    effective_date: string (date)
                    expiration_date: string (date)
                    description: string
                    rate: string
                    source: string
                    cap_applied_value: number
                    cap_option: string
                    threshold_applied_value: number
                    tax_entire_amount: boolean
                    options:
                      exemptions: array of string
                      additional_info: string
                    created_by_id: string
                    updated_by_id: string
                    created_at: string (datetime)
                    pdated_at: string (datetime)
        '400':
          description: Bad Request
        '404':
          description: Not Found.Tax Rule with that Specific ID not Found.
          content:
            application/json:
              schema:
                type: object
                example:
                  error: Tax Rule Not Found.
        '422':
          description: Unprocessable Entity. Validation errors occurred during the update.
          content:
            application/json:
              schema:
                type: object
                example:
                  errors: [ Product code can't be blank,Category is invalid ]
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Tax Rules
      summary: Delete Tax Rule
      description: This endpoint is used to delete a specific Tax Rule belonging to a tenant.
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Ok. Tax Rule Deleted successfully  
        '404':
          description: Not Found. Tax Rule with the Specific ID not Found.
          content:
            application/json:
              schema:
                type: object
                example:
                  error: Failed to delete the Tax Rule
        '500':
          description: Internal Server Error
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    TaxRule:
      type: object
      properties:
        name:
          type: string
          description: Name of the tax rule
        entity_id:
          type: string
          description: Unique identifier for the entity associated with the tax rule
        process_code:
          type: string
          description: Code representing the tax process
        tax_type_group:
          type: string
          description: Group or category of the tax type
        country:
          type: string
          description: Country where the tax rule is applicable
        region:
          type: string
          description: Region within the country where the tax rule applies
        jurisdiction_type:
          type: string
          description: Type of jurisdiction (e.g., State, City)
        juris_code:
          type: string
          description: Code representing the jurisdiction
        jurisdiction_name:
          type: string
          description: Name of the jurisdiction
        is_all_juris:
          type: boolean
          description: Indicates if the rule applies to all jurisdictions
        tax_code:
          type: string
          description: Code representing the tax
        tariff_code:
          type: string
          description: Code representing the tariff
        entity_use_code:
          type: string
          description: Code representing the entity use
        tax_type:
          type: string
          description: Type of tax (e.g., VAT, GST)
        rate_type:
          type: string
          description: Type of rate (e.g., Percentage, Fixed)
        value:
          type: number
          format: float
          description: Tax rate value
        threshold:
          type: number
          format: float
          description: Threshold amount for applying the tax
        cap:
          type: number
          format: float
          description: Maximum cap amount for the tax
        is_pro:
          type: boolean
          description: Indicates if the tax rule is professional-only
        effective_date:
          type: string
          format: date
          description: Date when the tax rule becomes effective
        expiration_date:
          type: string
          format: date
          description: Date when the tax rule expires
        description:
          type: string
          description: Detailed description of the tax rule
        rate:
          type: number
          format: float
          description: Tax rate percentage
        source:
          type: string
          description: Source of the tax rule information
        cap_applied_value:
          type: number
          format: float
          description: Applied value of the cap
        cap_option:
          type: string
          description: Option for the cap (e.g., Ceiling, Floor)
        threshold_applied_value:
          type: number
          format: float
          description: Applied value of the threshold
        tax_entire_amount:
          type: boolean
          description: Indicates if the tax is applied to the entire amount
        options:
          type: object
          properties:
            additional_info:
              type: string
              description: Additional information about the tax rule
            exemptions:
              type: array
              items:
                type: string
              description: List of exemptions for the tax rule
      required:
        - name
        - entity_id
        - process_code
        - tax_type_group
        - country
        - region
        - jurisdiction_type
        - juris_code
        - jurisdiction_name
        - tax_code
        - tax_type
        - rate_type
        - value
        - effective_date
        - expiration_date
        - description
    TaxRule1:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the tax rule
        name:
          type: string
          description: Name of the tax rule
        rule_type:
          type: string
          nullable: true
          description: Type of the rule
        process_code:
          type: string
          description: Unique process code for the tax rule
        tax_type_group:
          type: string
          description: Group classification of the tax type
        tax_sub_type:
          type: string
          nullable: true
          description: Subtype of the tax, if applicable
        country:
          type: string
          description: Country associated with the tax rule
        region:
          type: string
          description: Region within the country
        jurisdiction_type:
          type: string
          description: Type of jurisdiction (e.g., State, City)
        juris_code:
          type: string
          description: Jurisdiction code
        jurisdiction_name:
          type: string
          nullable: true
          description: Name of the jurisdiction
        is_all_juris:
          type: boolean
          description: Indicates if the rule applies to all jurisdictions
        tax_code:
          type: string
          description: Tax code associated with the rule
        tariff_code:
          type: string
          description: Tariff code associated with the rule
        entity_use_code:
          type: string
          description: Entity use code
        tax_type:
          type: string
          description: Type of tax (e.g., VAT, GST)
        rate_type:
          type: string
          description: Type of rate (e.g., Percentage, Fixed)
        value:
          type: number
          format: float
          description: Value of the tax rate
        threshold:
          type: number
          format: float
          description: Threshold value for the tax rule
        cap:
          type: number
          format: float
          description: Cap value for the tax rule
        options:
          type: object
          properties:
            exemptions:
              type: array
              items:
                type: string
              description: List of exemptions
            additional_info:
              type: string
              description: Additional information about the tax rule
        is_pro:
          type: boolean
          description: Indicates if the rule is provisional
        effective_date:
          type: string
          format: date
          description: Effective date of the rule
        expiration_date:
          type: string
          format: date
          description: Expiration date of the rule
        description:
          type: string
          description: Description of the tax rule
        rate:
          type: number
          format: float
          description: Rate value for the tax rule
        source:
          type: string
          description: Source of the tax rule
        created_by_id:
          type: string
          description: Identifier of the user who created the rule
        updated_by_id:
          type: string
          description: Identifier of the user who last updated the rule
        created_at:
          type: string
          format: date-time
          description: Date and time when the rule was created
        updated_at:
          type: string
          format: date-time
          description: Date and time when the rule was last updated
        entity_id:
          type: string
          description: Identifier of the associated entity
        cap_applied_value:
          type: number
          format: float
          description: Applied cap value
        cap_option:
          type: string
          description: Option applied to the cap (e.g., Ceiling, Floor)
        threshold_applied_value:
          type: number
          format: float
          description: Applied threshold value
        tax_entire_amount:
          type: boolean
          description: Indicates if the entire amount is taxable
      required:
        - id
        - name
        - process_code
        - tax_type_group
        - country
        - region
        - jurisdiction_type
        - juris_code
        - tax_code
        - tariff_code
        - tax_type
        - rate_type
        - value
        - effective_date
        - expiration_date
        - created_by_id
        - updated_by_id
        - created_at
        - updated_at
    TaxRule2:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the transaction rule
        name:
          type: string
          description: Name of the transaction rule
        entity_id:
          type: string
          description: Identifier for the associated entity
        rule_type:
          type: string
          nullable: true
          description: Type of rule
        process_code:
          type: string
          description: Process code associated with the rule
        tax_type_group:
          type: string
          description: Tax type group classification
        tax_sub_type:
          type: string
          nullable: true
          description: Sub-type of the tax
        country:
          type: string
          description: Country for the rule
        region:
          type: string
          description: Region for the rule
        jurisdiction_type:
          type: string
          description: Jurisdiction type (e.g., State, City)
        juris_code:
          type: string
          description: Jurisdiction code
        jurisdiction_name:
          type: string
          nullable: true
          description: Name of the jurisdiction
        is_all_juris:
          type: boolean
          description: Whether the rule applies to all jurisdictions
        tax_code:
          type: string
          description: Code for the tax
        tariff_code:
          type: string
          description: Code for the tariff
        entity_use_code:
          type: string
          description: Entity use code
        tax_type:
          type: string
          description: Tax type
        rate_type:
          type: string
          description: Type of rate (e.g., Percentage, Fixed)
        value:
          type: number
          description: Tax value or rate
        threshold:
          type: number
          description: Threshold amount
        cap:
          type: number
          description: Cap amount for the tax
        is_pro:
          type: boolean
          description: Whether the rule is promotional
        effective_date:
          type: string
          format: date
          description: Start date of the rule
        expiration_date:
          type: string
          format: date
          description: End date of the rule
        description:
          type: string
          description: Description of the rule
        rate:
          type: number
          description: Tax rate
        source:
          type: string
          description: Source of the rule
        cap_applied_value:
          type: number
          description: Value of the cap applied
        cap_option:
          type: string
          description: Cap option (e.g., Ceiling, Floor)
        threshold_applied_value:
          type: number
          description: Threshold applied value
        tax_entire_amount:
          type: boolean
          description: Whether the tax applies to the entire amount
        options:
          type: object
          properties:
            exemptions:
              type: array
              items:
                type: string
              description: List of exempted items
            additional_info:
              type: string
              description: Additional information about the rule
        created_by_id:
          type: string
          description: Identifier of the user who created the rule
        updated_by_id:
          type: string
          description: Identifier of the user who last updated the rule
        created_at:
          type: string
          format: date-time
          description: Date and time when the rule was created
        updated_at:
          type: string
          format: date-time
          description: Date and time when the rule was last updated
      required:
        - id
        - name
        - entity_id
        - process_code
        - tax_type_group
        - country
        - region
        - jurisdiction_type
        - juris_code
        - tax_code
        - tariff_code
        - entity_use_code
        - tax_type
        - rate_type
        - value
        - effective_date
        - expiration_date
        - created_by_id
        - updated_by_id
        - created_at
        - updated_at
    