openapi: 3.0.0
info:
  title: ScalarTax
  description : Subscriptions API Documentation
  version: 1.0.0
  contact:
    name: API Support
    url: http://example.com/supportt
    email: support@example.com
  termsOfService: http://example.com/terms/
servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: http://{{base_url}}/
    description: Local server
paths:
  /scalartax/subscriptions:
    post:
      tags:
        - Subscriptions
      summary: Create Subscription
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Subscription"
        description: Subscription object
        required: true
      responses:
        '201':
          description: Subscription Created Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
                example:
                  id: string
                  name: string
                  contract_acceptance_date: datetime
                  contract_termination_date: datetime
                  contract_effective_date: datetime
                  contract_end_date: datetime
                  service_activation_date: datetime
                  service_end_date: datetime
                  status: string
                  billing_cycle: string
                  billing_amount: boolean
                  created_by_id: string
                  updated_by_id: string
                  created_at: datetime
                  updated_at: datetime
        '422':
          description:  Unprocessable Entity. Validation errors occurred during the creation.
          content:
            application/json:
              schema:
                type: object
                example:
                  errors: [ { name : [can't be blank],account_id : [must exist]} ]
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    get:
      tags:
        - Subscriptions
      summary: List Subscriptions
      description: This endpoint retrieves a list of subscriptions related to scalar tax.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subscription"
                example: 
                  - id: string
                    name: string
                    contract_acceptance_date: datetime
                    contract_termination_date: datetime
                    contract_effective_date: datetime
                    contract_end_date: datetime
                    service_activation_date: datetime
                    service_end_date: datetime
                    status: string
                    billing_cycle: string
                    billing_amount: boolean
                    created_by_id: string
                    updated_by_id: string
                    created_at: datetime
                    updated_at: datetime

        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /scalartax/subscriptions/{id}:
    get:
      tags:
        - Subscriptions
      summary: Fetch Subscription
      description: This API provides access to subscription information.
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subscription"
                example: 
                  id: string
                  name: string
                  contract_acceptance_date: datetime
                  contract_termination_date: datetime
                  contract_effective_date: datetime
                  contract_end_date: datetime
                  service_activation_date: datetime
                  service_end_date: datetime
                  status: string
                  billing_cycle: string
                  billing_amount: boolean
                  created_by_id: string
                  updated_by_id: string
                  created_at: datetime
                  updated_at: datetime
        '404':
          description: Not Found. Subscription with that Specific ID not Found.
          content:
            application/json:
              schema:
                type: object
                example:
                  error: Subscription Not Found.
        '500':
          description: Internal Serval Error.
    put:
      tags:
        - Subscriptions
      summary: Update Subscription
      description: This API endpoint is used to update the details of a specific Transaction.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Subscription"
        required: true
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK. Subscription Updated Successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subscription"
                example:
                  name: string
                  contract_acceptance_date: datetime
                  contract_termination_date: datetime
                  contract_effective_date: datetime
                  contract_end_date: datetime
                  service_activation_date: datetime
                  service_end_date: datetime
                  status: string
                  billing_cycle: string
                  billing_amount: boolean
                  created_by_id: string
                  updated_by_id: string
                  id: string
                  created_at: datetime
                  updated_at: datetime
        '400':
          description: Bad Request
        '404':
          description: Not Found.Customer with that Specific ID not Found.
          content:
            application/json:
              schema:
                type: object
                example:
                  error: Customer Not Found.
        '422':
          description: Unprocessable Entity. Validation errors occurred during the update.
          content:
            application/json:
              schema:
                type: object
                example:
                  errors: [ { ststus : [ is invalid ] } ]
        '500':
          description: Internal Server Error
    delete: 
      tags:
        - Subscriptions
      summary: Delete Subscription
      description: This endpoint sends an HTTP DELETE request to the specified subscription ID 
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Ok. Subscription deleted successfully
        '404':
          description: Not Found. Subscription with the Specific ID not Found.
          content:
            application/json:
              schema:
                type: object
                example:
                  error: Subscription Not Found.
        '500':
          description: Internal Server Error
components:
  schemas:
    Subscription:
      type: object
      properties:
        subscription:
          type: object
          properties:
            name:
              type: string
              description: Name of the subscription
              required: true
            contract_acceptance_date:
              type: string
              format: date-time
              description: The date when the contract was accepted
              required: true
            contract_termination_date:
              type: string
              format: date-time
              description: The date when the contract was terminated
              required: false
            contract_effective_date:
              type: string
              format: date-time
              description: The date when the contract becomes effective
              required: true
            contract_end_date:
              type: string
              format: date-time
              description: The date when the contract ends
              required: true
            service_activation_date:
              type: string
              format: date-time
              description: The date when the service is activated
              required: true
            service_end_date:
              type: string
              format: date-time
              description: The date when the service ends
              required: true
            status:
              type: string
              description: Current status of the subscription
              required: true
            billing_cycle:
              type: string
              description: The billing cycle (e.g., monthly, yearly)
              required: true
            billing_amount:
              type: boolean
              description: Indicates if billing is enabled or not
              required: true
            created_by_id:
              type: string
              description: ID of the user who created the subscription
              required: false
            updated_by_id:
              type: string
              description: ID of the user who last updated the subscription
              required: false
          required:
            - name
            - contract_acceptance_date
            - contract_termination_date
            - contract_effective_date
            - contract_end_date
            - service_activation_date
            - service_end_date
            - status
            - billing_cycle
            - billing_amount
            - created_by_id
            - updated_by_id
      required:
        - subscription
  